# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#target-branch

version: 2

updates:
  - allow:
      - dependency-type: "direct"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    package-ecosystem: composer
    schedule:
      interval: daily
    versioning-strategy: "lockfile-only"
