git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/bin

branches:
    only:
        - master
        - /^v?\d+\.\d+(\.\d+)?$/ # and versions (tags)

stages:
    - test
    - build

jobs:
    include:
        -   stage: test
            name: Static analysis
            language: php
            php: 7.1
            before_install:
                - phpenv config-rm xdebug.ini
            install:
                - composer install -o
                - wget --no-clobber --output-document=$HOME/bin/php-cs-fixer https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar || true
                - chmod +x $HOME/bin/php-cs-fixer
                - wget --no-clobber --output-document=$HOME/bin/phpstan https://github.com/phpstan/phpstan/releases/download/0.11.2/phpstan.phar || true
                - chmod +x $HOME/bin/phpstan
            script:
                - $HOME/bin/php-cs-fixer fix --config=.php_cs.dist --dry-run --diff -v --using-cache=no
                - $HOME/bin/phpstan analyze

        -   stage: test
            name: Unit tests (7.1)
            language: php
            php: 7.1
            install:
                - make tests

        -   stage: test
            name: Unit tests (7.2)
            language: php
            php: 7.2
            install:
                - make tests

        -   stage: test
            name: Unit tests (7.3)
            language: php
            php: 7.3
            install:
                - make tests

        -   stage: build
            language: php
            php: 7.1
            before_install:
                - phpenv config-rm xdebug.ini
            install:
                - composer install -o
                - wget --no-clobber --output-document=$HOME/bin/box https://github.com/humbug/box/releases/download/3.4.0/box.phar || true
                - chmod +x $HOME/bin/box
            script:
                - $HOME/bin/box compile
                - php deptrac.phar analyze examples/Fixture.depfile.yml --no-cache
                - "[ ! -f '.deptrac.cache' ]"
                - php deptrac.phar analyze examples/Fixture.depfile.yml
                - "[ -f '.deptrac.cache' ]"
                - php deptrac.phar analyze examples/Fixture.depfile.yml # test with cache file
                - php deptrac.phar analyze examples/Fixture.depfile.yml --cache-file=.deptrac.cache2
                - "[ -f '.deptrac.cache2' ]"
