site_name: Deptrac
site_description: "Deptrac: keep your architecture clean"
site_url: https://qossmic.github.io/deptrac

repo_name: 'qossmic/deptrac'
repo_url: 'https://github.com/qossmic/deptrac'
edit_uri: ''

docs_dir: docs

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Depfile: depfile.md
  - Collectors: collectors.md
  - Formatters: formatters.md
  - Debugging: debugging.md
  - Contributing: contributing.md

theme:
  name: material
  logo: qossmic.png
  extra:
    homepage: https://qossmic.com
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
